Tags subscribe
ilyatos/freelansim-bot pull request #21
Opened 2018-06-24 13:13 UTC by ilyatos

2018-06-24 13:20 UTC, 13Tenseii approved these changes

2018-06-24 14:33 UTC, vladthelittleone requested changes

2018-06-24 14:33 UTC, vladthelittleone commented on app/botManager.php
> +                        $sms->sendMessage('Вы уже подписаны на тег: `'.$tag.'`');
Метод должен помещаться на экран. Дели их на подметоды

2018-06-24 19:32 UTC, ilyatos commented on app/botManager.php
> +                        $sms->sendMessage('Вы уже подписаны на тег: `'.$tag.'`');
не очень понял

2019-01-19 15:46 UTC, merged

2019-01-19 22:54 UTC, vladthelittleone commented
@ilyatos лол)